# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anssea.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Anssea
  avatar: avatar.png
  gravatar: # email md5 hash
  description: "Mi blog. - Un romántico, un tecno, un cientifico, un católico, un exacto, un soñador, un hombre - sea" # used by search engines
  
  # Header and footer text
  header_text: >
     <p>- Un romántico, un tecno, un cientifico, un católico, un exacto, un soñador, un hombre - <em>sea</em></p>
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  
  # Icons
  rss: false
  email_address: "anssea@outlook.com" # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "anssea/anssea.github.io"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "anssea"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname:
  
  # Localization strings
  str_follow_on: "Seguirme en"
  str_rss_follow: "RSS feed"
  str_email: "Email"
  str_next: "Siguiente"
  str_prev: "Anterior"
  str_continue_reading: "Seguir leyendo"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
